/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereVappEntityObservation struct {

	// Managed object ID of the vApp container the entity is a member of.
	ContainerID *string `json:"containerId,omitempty" tf:"container_id,omitempty"`

	// A list of custom attributes to set on this resource.
	CustomAttributes map[string]*string `json:"customAttributes,omitempty" tf:"custom_attributes,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// How to start the entity. Valid settings are none or powerOn. If set to none, then the entity does not participate in auto-start.
	StartAction *string `json:"startAction,omitempty" tf:"start_action,omitempty"`

	// Delay in seconds before continuing with the next entity in the order of entities to be started.
	StartDelay *float64 `json:"startDelay,omitempty" tf:"start_delay,omitempty"`

	// Order to start and stop target in vApp.
	StartOrder *float64 `json:"startOrder,omitempty" tf:"start_order,omitempty"`

	// Defines the stop action for the entity. Can be set to none, powerOff, guestShutdown, or suspend. If set to none, then the entity does not participate in auto-stop.
	StopAction *string `json:"stopAction,omitempty" tf:"stop_action,omitempty"`

	// Delay in seconds before continuing with the next entity in the order of entities to be stopped.
	StopDelay *float64 `json:"stopDelay,omitempty" tf:"stop_delay,omitempty"`

	// A list of tag IDs to apply to this object.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Managed object ID of the entity to power on or power off. This can be a virtual machine or a vApp.
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// Determines if the VM should be marked as being started when VMware Tools are ready instead of waiting for start_delay. This property has no effect for vApps.
	WaitForGuest *bool `json:"waitForGuest,omitempty" tf:"wait_for_guest,omitempty"`
}

type VSphereVappEntityParameters struct {

	// Managed object ID of the vApp container the entity is a member of.
	// +kubebuilder:validation:Optional
	ContainerID *string `json:"containerId,omitempty" tf:"container_id,omitempty"`

	// A list of custom attributes to set on this resource.
	// +kubebuilder:validation:Optional
	CustomAttributes map[string]*string `json:"customAttributes,omitempty" tf:"custom_attributes,omitempty"`

	// How to start the entity. Valid settings are none or powerOn. If set to none, then the entity does not participate in auto-start.
	// +kubebuilder:validation:Optional
	StartAction *string `json:"startAction,omitempty" tf:"start_action,omitempty"`

	// Delay in seconds before continuing with the next entity in the order of entities to be started.
	// +kubebuilder:validation:Optional
	StartDelay *float64 `json:"startDelay,omitempty" tf:"start_delay,omitempty"`

	// Order to start and stop target in vApp.
	// +kubebuilder:validation:Optional
	StartOrder *float64 `json:"startOrder,omitempty" tf:"start_order,omitempty"`

	// Defines the stop action for the entity. Can be set to none, powerOff, guestShutdown, or suspend. If set to none, then the entity does not participate in auto-stop.
	// +kubebuilder:validation:Optional
	StopAction *string `json:"stopAction,omitempty" tf:"stop_action,omitempty"`

	// Delay in seconds before continuing with the next entity in the order of entities to be stopped.
	// +kubebuilder:validation:Optional
	StopDelay *float64 `json:"stopDelay,omitempty" tf:"stop_delay,omitempty"`

	// A list of tag IDs to apply to this object.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Managed object ID of the entity to power on or power off. This can be a virtual machine or a vApp.
	// +kubebuilder:validation:Optional
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// Determines if the VM should be marked as being started when VMware Tools are ready instead of waiting for start_delay. This property has no effect for vApps.
	// +kubebuilder:validation:Optional
	WaitForGuest *bool `json:"waitForGuest,omitempty" tf:"wait_for_guest,omitempty"`
}

// VSphereVappEntitySpec defines the desired state of VSphereVappEntity
type VSphereVappEntitySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereVappEntityParameters `json:"forProvider"`
}

// VSphereVappEntityStatus defines the observed state of VSphereVappEntity.
type VSphereVappEntityStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereVappEntityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereVappEntity is the Schema for the VSphereVappEntitys API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereVappEntity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.containerId)",message="containerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.targetId)",message="targetId is a required parameter"
	Spec   VSphereVappEntitySpec   `json:"spec"`
	Status VSphereVappEntityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereVappEntityList contains a list of VSphereVappEntitys
type VSphereVappEntityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereVappEntity `json:"items"`
}

// Repository type metadata.
var (
	VSphereVappEntity_Kind             = "VSphereVappEntity"
	VSphereVappEntity_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereVappEntity_Kind}.String()
	VSphereVappEntity_KindAPIVersion   = VSphereVappEntity_Kind + "." + CRDGroupVersion.String()
	VSphereVappEntity_GroupVersionKind = CRDGroupVersion.WithKind(VSphereVappEntity_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereVappEntity{}, &VSphereVappEntityList{})
}
