/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereContentLibraryItemObservation struct {

	// Optional description of the content library item.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of source VM of content library item.
	FileURL *string `json:"fileUrl,omitempty" tf:"file_url,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of the content library to contain item
	LibraryID *string `json:"libraryId,omitempty" tf:"library_id,omitempty"`

	// The name of the content library item.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The managed object ID of an existing VM to be cloned to the content library.
	SourceUUID *string `json:"sourceUuid,omitempty" tf:"source_uuid,omitempty"`

	// Type of content library item.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VSphereContentLibraryItemParameters struct {

	// Optional description of the content library item.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of source VM of content library item.
	// +kubebuilder:validation:Optional
	FileURL *string `json:"fileUrl,omitempty" tf:"file_url,omitempty"`

	// ID of the content library to contain item
	// +kubebuilder:validation:Optional
	LibraryID *string `json:"libraryId,omitempty" tf:"library_id,omitempty"`

	// The name of the content library item.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The managed object ID of an existing VM to be cloned to the content library.
	// +kubebuilder:validation:Optional
	SourceUUID *string `json:"sourceUuid,omitempty" tf:"source_uuid,omitempty"`

	// Type of content library item.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// VSphereContentLibraryItemSpec defines the desired state of VSphereContentLibraryItem
type VSphereContentLibraryItemSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereContentLibraryItemParameters `json:"forProvider"`
}

// VSphereContentLibraryItemStatus defines the observed state of VSphereContentLibraryItem.
type VSphereContentLibraryItemStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereContentLibraryItemObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereContentLibraryItem is the Schema for the VSphereContentLibraryItems API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereContentLibraryItem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.libraryId)",message="libraryId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   VSphereContentLibraryItemSpec   `json:"spec"`
	Status VSphereContentLibraryItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereContentLibraryItemList contains a list of VSphereContentLibraryItems
type VSphereContentLibraryItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereContentLibraryItem `json:"items"`
}

// Repository type metadata.
var (
	VSphereContentLibraryItem_Kind             = "VSphereContentLibraryItem"
	VSphereContentLibraryItem_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereContentLibraryItem_Kind}.String()
	VSphereContentLibraryItem_KindAPIVersion   = VSphereContentLibraryItem_Kind + "." + CRDGroupVersion.String()
	VSphereContentLibraryItem_GroupVersionKind = CRDGroupVersion.WithKind(VSphereContentLibraryItem_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereContentLibraryItem{}, &VSphereContentLibraryItemList{})
}
