apiVersion: vsphere.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: vsphere
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
