/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this VSphereDistributedPortGroup
func (mg *VSphereDistributedPortGroup) GetTerraformResourceType() string {
	return "vsphere_distributed_port_group"
}

// GetConnectionDetailsMapping for this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereDistributedPortGroup
func (tr *VSphereDistributedPortGroup) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereDistributedPortGroup using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereDistributedPortGroup) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereDistributedPortGroupParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereDistributedPortGroup) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this VSphereDistributedVirtualSwitch
func (mg *VSphereDistributedVirtualSwitch) GetTerraformResourceType() string {
	return "vsphere_distributed_virtual_switch"
}

// GetConnectionDetailsMapping for this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereDistributedVirtualSwitch
func (tr *VSphereDistributedVirtualSwitch) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereDistributedVirtualSwitch using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereDistributedVirtualSwitch) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereDistributedVirtualSwitchParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereDistributedVirtualSwitch) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this VSphereHostPortGroup
func (mg *VSphereHostPortGroup) GetTerraformResourceType() string {
	return "vsphere_host_port_group"
}

// GetConnectionDetailsMapping for this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereHostPortGroup
func (tr *VSphereHostPortGroup) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereHostPortGroup using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereHostPortGroup) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereHostPortGroupParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereHostPortGroup) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this VSphereHostVirtualSwitch
func (mg *VSphereHostVirtualSwitch) GetTerraformResourceType() string {
	return "vsphere_host_virtual_switch"
}

// GetConnectionDetailsMapping for this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereHostVirtualSwitch
func (tr *VSphereHostVirtualSwitch) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereHostVirtualSwitch using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereHostVirtualSwitch) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereHostVirtualSwitchParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereHostVirtualSwitch) GetTerraformSchemaVersion() int {
	return 0
}
