/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereComputeClusterVmAffinityRuleObservation struct {

	// The managed object ID of the cluster.
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When true, prevents any virtual machine operations that may violate this rule.
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run on the same host together.
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

type VSphereComputeClusterVmAffinityRuleParameters struct {

	// The managed object ID of the cluster.
	// +kubebuilder:validation:Optional
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When true, prevents any virtual machine operations that may violate this rule.
	// +kubebuilder:validation:Optional
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run on the same host together.
	// +kubebuilder:validation:Optional
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

// VSphereComputeClusterVmAffinityRuleSpec defines the desired state of VSphereComputeClusterVmAffinityRule
type VSphereComputeClusterVmAffinityRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereComputeClusterVmAffinityRuleParameters `json:"forProvider"`
}

// VSphereComputeClusterVmAffinityRuleStatus defines the observed state of VSphereComputeClusterVmAffinityRule.
type VSphereComputeClusterVmAffinityRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereComputeClusterVmAffinityRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmAffinityRule is the Schema for the VSphereComputeClusterVmAffinityRules API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereComputeClusterVmAffinityRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.computeClusterId)",message="computeClusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.virtualMachineIds)",message="virtualMachineIds is a required parameter"
	Spec   VSphereComputeClusterVmAffinityRuleSpec   `json:"spec"`
	Status VSphereComputeClusterVmAffinityRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmAffinityRuleList contains a list of VSphereComputeClusterVmAffinityRules
type VSphereComputeClusterVmAffinityRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereComputeClusterVmAffinityRule `json:"items"`
}

// Repository type metadata.
var (
	VSphereComputeClusterVmAffinityRule_Kind             = "VSphereComputeClusterVmAffinityRule"
	VSphereComputeClusterVmAffinityRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereComputeClusterVmAffinityRule_Kind}.String()
	VSphereComputeClusterVmAffinityRule_KindAPIVersion   = VSphereComputeClusterVmAffinityRule_Kind + "." + CRDGroupVersion.String()
	VSphereComputeClusterVmAffinityRule_GroupVersionKind = CRDGroupVersion.WithKind(VSphereComputeClusterVmAffinityRule_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereComputeClusterVmAffinityRule{}, &VSphereComputeClusterVmAffinityRuleList{})
}
