/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereComputeClusterVmGroupObservation struct {

	// The managed object ID of the cluster.
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines in this group.
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

type VSphereComputeClusterVmGroupParameters struct {

	// The managed object ID of the cluster.
	// +kubebuilder:validation:Optional
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines in this group.
	// +kubebuilder:validation:Optional
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

// VSphereComputeClusterVmGroupSpec defines the desired state of VSphereComputeClusterVmGroup
type VSphereComputeClusterVmGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereComputeClusterVmGroupParameters `json:"forProvider"`
}

// VSphereComputeClusterVmGroupStatus defines the observed state of VSphereComputeClusterVmGroup.
type VSphereComputeClusterVmGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereComputeClusterVmGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmGroup is the Schema for the VSphereComputeClusterVmGroups API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereComputeClusterVmGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.computeClusterId)",message="computeClusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   VSphereComputeClusterVmGroupSpec   `json:"spec"`
	Status VSphereComputeClusterVmGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmGroupList contains a list of VSphereComputeClusterVmGroups
type VSphereComputeClusterVmGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereComputeClusterVmGroup `json:"items"`
}

// Repository type metadata.
var (
	VSphereComputeClusterVmGroup_Kind             = "VSphereComputeClusterVmGroup"
	VSphereComputeClusterVmGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereComputeClusterVmGroup_Kind}.String()
	VSphereComputeClusterVmGroup_KindAPIVersion   = VSphereComputeClusterVmGroup_Kind + "." + CRDGroupVersion.String()
	VSphereComputeClusterVmGroup_GroupVersionKind = CRDGroupVersion.WithKind(VSphereComputeClusterVmGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereComputeClusterVmGroup{}, &VSphereComputeClusterVmGroupList{})
}
