/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereComputeClusterVmAntiAffinityRuleObservation struct {

	// The managed object ID of the cluster.
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When true, prevents any virtual machine operations that may violate this rule.
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run on hosts different from each other.
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

type VSphereComputeClusterVmAntiAffinityRuleParameters struct {

	// The managed object ID of the cluster.
	// +kubebuilder:validation:Optional
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When true, prevents any virtual machine operations that may violate this rule.
	// +kubebuilder:validation:Optional
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The unique name of the virtual machine group in the cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run on hosts different from each other.
	// +kubebuilder:validation:Optional
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

// VSphereComputeClusterVmAntiAffinityRuleSpec defines the desired state of VSphereComputeClusterVmAntiAffinityRule
type VSphereComputeClusterVmAntiAffinityRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereComputeClusterVmAntiAffinityRuleParameters `json:"forProvider"`
}

// VSphereComputeClusterVmAntiAffinityRuleStatus defines the observed state of VSphereComputeClusterVmAntiAffinityRule.
type VSphereComputeClusterVmAntiAffinityRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereComputeClusterVmAntiAffinityRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmAntiAffinityRule is the Schema for the VSphereComputeClusterVmAntiAffinityRules API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereComputeClusterVmAntiAffinityRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.computeClusterId)",message="computeClusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.virtualMachineIds)",message="virtualMachineIds is a required parameter"
	Spec   VSphereComputeClusterVmAntiAffinityRuleSpec   `json:"spec"`
	Status VSphereComputeClusterVmAntiAffinityRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmAntiAffinityRuleList contains a list of VSphereComputeClusterVmAntiAffinityRules
type VSphereComputeClusterVmAntiAffinityRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereComputeClusterVmAntiAffinityRule `json:"items"`
}

// Repository type metadata.
var (
	VSphereComputeClusterVmAntiAffinityRule_Kind             = "VSphereComputeClusterVmAntiAffinityRule"
	VSphereComputeClusterVmAntiAffinityRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereComputeClusterVmAntiAffinityRule_Kind}.String()
	VSphereComputeClusterVmAntiAffinityRule_KindAPIVersion   = VSphereComputeClusterVmAntiAffinityRule_Kind + "." + CRDGroupVersion.String()
	VSphereComputeClusterVmAntiAffinityRule_GroupVersionKind = CRDGroupVersion.WithKind(VSphereComputeClusterVmAntiAffinityRule_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereComputeClusterVmAntiAffinityRule{}, &VSphereComputeClusterVmAntiAffinityRuleList{})
}
